baseURL = "http://s3hugo.s3-website-us-east-2.amazonaws.com"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"

[[deployment.targets]]
# An arbitrary name for this target.
name = "awsbucket"
URL = "s3://s3hugo/?region=us-east-2" #your bucket here